%create figure template
delete(allchild(0))
figureName='Burst Analyses';

fontName = 'Arial';
fontSize = 6;
lineWidth = 0.05;
screenWH=get(0,'ScreenSize');%pixels
margin = 40;
figureWidth = screenWH(3)-2*margin;
figureHeight = screenWH(4)-2*margin;
figurePos = [margin margin figureWidth figureHeight];

set(0,'units','pixels')
set(0,'defaulttextfontsize',fontSize,...
   'defaultaxesfontsize',fontSize,...
   'defaulttextfontname',fontName,...
   'defaultaxeslinewidth',lineWidth)

%Main figure window
H_Figure=figure('Position',figurePos,...
                'PaperOrientation', 'Landscape',...
                'NumberTitle','off',...
                'Menu','none',...
                'Units','normalized',...
                'Name',figureName,...
                'Color',[1 1 1],...
                'Tag','H_Figure');
% OutlinePos=[0.005 0.005 0.99 0.99];
% H_Outline=axes('parent',H_Figure,...
%                'position',OutlinePos,...
%                'box','on',...
%                'xtick',[],...
%                'ytick',[],...
%                'xcolor',[0 0 0],...
%                'ycolor',[0 0 0],...
%                'Tag','H_Outline');
           
xGutter = 0.02; 
yGutter = 0.04;
nCols = 4;
plotW = (1/nCols) - 1.5 * xGutter;
nRows = 2;
plotH = (1/nRows) - 1.5 * yGutter;
plotX = ((0:nCols-1).*(1/nCols)) + xGutter;
plotX = repmat(plotX,nRows,1);
plotY = ((0:nRows-1).*(1/nRows)) + yGutter;
plotY = repmat(plotY(:),1,nCols);

H1 = arrayfun(@(x) axes('Parent',H_Figure,...
                       'Position',[plotX(2,x) plotY(2,x) plotW plotH],...
                       'Box','on',...
                       'Tag',['H_' num2str(x)]),...
                       (1:4),'UniformOutput',false);
H2 = arrayfun(@(x) axes('Parent',H_Figure,...
                       'Position',[plotX(1,x) plotY(1,x) plotW plotH],...
                       'Box','on',...
                       'Tag',['H_' num2str(x+4)]),...
                       (1:4),'UniformOutput',false);
H_Plots = [H1{:} H2{:}];

           



